version: '3.8'
services:

  # Servicio de la base de datos PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio de la aplicación de Node.js
  app:
    build: .
    container_name: prueba_tecnica
    image: prueba_tecnica:latest
    command: bash -c "npm install && npm start"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app_network
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: